<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UMWB4usService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.uMWB4us' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uMWB4us'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['privates', '.errored.vnCFgv8', NULL, 'Cannot determine controller argument for "Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::mongoUpdate()": the $entityManager argument is type-hinted with the non-existent class or interface: "Doctrine\\ODM\\MongoDB\\DocumentManager".'],
        ], [
            'entityManager' => '?',
        ]);
    }
}
