<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_VnCFgv8Service extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.errored.vnCFgv8' shared service.
     *
     * @return \Doctrine\ODM\MongoDB\DocumentManager
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::mongoUpdate()": the $entityManager argument is type-hinted with the non-existent class or interface: "Doctrine\\ODM\\MongoDB\\DocumentManager".');
    }
}
