<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Persistence_DatabaseResetter_Orm_Dama_InnerService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.zenstruck_foundry.persistence.database_resetter.orm.dama.inner' shared service.
     *
     * @return \Zenstruck\Foundry\ORM\ResetDatabase\SchemaDatabaseResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Persistence/ResetDatabase/BeforeFirstTestResetter.php';
        include_once \dirname(__DIR__, 6).'/Persistence/ResetDatabase/BeforeEachTestResetter.php';
        include_once \dirname(__DIR__, 6).'/ORM/ResetDatabase/OrmResetter.php';
        include_once \dirname(__DIR__, 6).'/ORM/ResetDatabase/BaseOrmResetter.php';
        include_once \dirname(__DIR__, 6).'/ORM/ResetDatabase/SchemaDatabaseResetter.php';

        return $container->privates['.zenstruck_foundry.persistence.database_resetter.orm.dama.inner'] = new \Zenstruck\Foundry\ORM\ResetDatabase\SchemaDatabaseResetter(($container->services['doctrine'] ?? $container->load('getDoctrineService')), ['default'], ['default']);
    }
}
