<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Story_FixtureResolverService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public '.zenstruck_foundry.story.fixture_resolver' shared service.
     *
     * @return \Zenstruck\Foundry\Story\FixtureStoryResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Story/FixtureStoryResolver.php';

        return $container->services['.zenstruck_foundry.story.fixture_resolver'] = new \Zenstruck\Foundry\Story\FixtureStoryResolver(['behat-category' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\CategoryStory', 'conflict-story-1' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory1', 'conflict-story-2' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory2', 'behat-contacts' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ContactStory'], ['behat-stories' => ['behat-category' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\CategoryStory', 'behat-contacts' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ContactStory'], 'conflict-test' => ['conflict-story-1' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory1', 'conflict-story-2' => 'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory2']]);
    }
}
