<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Persistence_DatabaseResetter_Orm_DamaService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.zenstruck_foundry.persistence.database_resetter.orm.dama' shared service.
     *
     * @return \Zenstruck\Foundry\ORM\ResetDatabase\DamaDatabaseResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Persistence/ResetDatabase/BeforeFirstTestResetter.php';
        include_once \dirname(__DIR__, 6).'/Persistence/ResetDatabase/BeforeEachTestResetter.php';
        include_once \dirname(__DIR__, 6).'/ORM/ResetDatabase/OrmResetter.php';
        include_once \dirname(__DIR__, 6).'/ORM/ResetDatabase/DamaDatabaseResetter.php';

        return $container->privates['.zenstruck_foundry.persistence.database_resetter.orm.dama'] = new \Zenstruck\Foundry\ORM\ResetDatabase\DamaDatabaseResetter(($container->privates['.zenstruck_foundry.persistence.database_resetter.orm.dama.inner'] ?? $container->load('get_ZenstruckFoundry_Persistence_DatabaseResetter_Orm_Dama_InnerService')), $container->targetDir.'');
    }
}
