<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DHHNk2Service extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.dHH_Nk2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dHH_Nk2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\BehatTestKernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\BehatTestKernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::ormUpdate' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::ormUpdate()', 'getUpdateGenericModelormUpdateService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::mongoUpdate' => ['privates', '.service_locator.uMWB4us', 'get_ServiceLocator_UMWB4usService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::ormCreate' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::ormCreate()', 'getCreateGenericModelormCreateService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::mongoCreate' => ['privates', '.service_locator.M.5L_Ia', 'get_ServiceLocator_M_5LIaService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDelete' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDelete()', 'getDeleteGenericModelormDeleteService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::mongoDelete' => ['privates', '.service_locator.Ejuwjyn', 'get_ServiceLocator_EjuwjynService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDbDelete' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDbDelete()', 'getDeleteGenericModelormDbDeleteService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::mongoDbDelete' => ['privates', '.service_locator.D546w5x', 'get_ServiceLocator_D546w5xService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel:ormUpdate' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::ormUpdate()', 'getUpdateGenericModelormUpdateService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel:mongoUpdate' => ['privates', '.service_locator.uMWB4us', 'get_ServiceLocator_UMWB4usService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel:ormCreate' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::ormCreate()', 'getCreateGenericModelormCreateService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel:mongoCreate' => ['privates', '.service_locator.M.5L_Ia', 'get_ServiceLocator_M_5LIaService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:ormDelete' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDelete()', 'getDeleteGenericModelormDeleteService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:mongoDelete' => ['privates', '.service_locator.Ejuwjyn', 'get_ServiceLocator_EjuwjynService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:ormDbDelete' => ['privates', '.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDbDelete()', 'getDeleteGenericModelormDbDeleteService', true],
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:mongoDbDelete' => ['privates', '.service_locator.D546w5x', 'get_ServiceLocator_D546w5xService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\BehatTestKernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\BehatTestKernel::loadRoutes' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::ormUpdate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel::mongoUpdate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::ormCreate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::mongoCreate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDelete' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::mongoDelete' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDbDelete' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::mongoDbDelete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel:ormUpdate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel:mongoUpdate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel:ormCreate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel:mongoCreate' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:ormDelete' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:mongoDelete' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:ormDbDelete' => '?',
            'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel:mongoDbDelete' => '?',
        ]);
    }
}
