<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Behat_ObjectRegistryService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public '.zenstruck_foundry.behat.object_registry' shared service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\ObjectRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ObjectRegistry.php';

        return $container->services['.zenstruck_foundry.behat.object_registry'] = new \Zenstruck\Foundry\Test\Behat\ObjectRegistry(($container->services['.zenstruck_foundry.behat.factory_resolver'] ?? $container->load('get_ZenstruckFoundry_Behat_FactoryResolverService')), ($container->services['Zenstruck\\Foundry\\Persistence\\PersistenceManager'] ?? $container->load('getPersistenceManagerService')));
    }
}
