<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_PersistenceStrategy_OrmService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.zenstruck_foundry.persistence_strategy.orm' shared service.
     *
     * @return \Zenstruck\Foundry\ORM\OrmV3PersistenceStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Persistence/PersistenceStrategy.php';
        include_once \dirname(__DIR__, 6).'/ORM/AbstractORMPersistenceStrategy.php';
        include_once \dirname(__DIR__, 6).'/ORM/OrmV3PersistenceStrategy.php';

        return $container->privates['.zenstruck_foundry.persistence_strategy.orm'] = new \Zenstruck\Foundry\ORM\OrmV3PersistenceStrategy(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
