<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Command_LoadFixturesService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.zenstruck_foundry.command.load_fixtures' shared service.
     *
     * @return \Zenstruck\Foundry\Command\LoadFixturesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/Command/LoadFixturesCommand.php';

        $container->privates['.zenstruck_foundry.command.load_fixtures'] = $instance = new \Zenstruck\Foundry\Command\LoadFixturesCommand(($container->services['.zenstruck_foundry.story.fixture_resolver'] ?? $container->load('get_ZenstruckFoundry_Story_FixtureResolverService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.zenstruck_foundry.persistence.database_resetter.orm.dama'] ?? $container->load('get_ZenstruckFoundry_Persistence_DatabaseResetter_Orm_DamaService'));
        }, 1), ($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->setName('foundry:load-fixtures');
        $instance->setAliases(['foundry:load-stories', 'foundry:load-story']);
        $instance->setDescription('Load stories which are marked with #[AsFixture] attribute.');

        return $instance;
    }
}
