<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M_5LIaService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.M.5L_Ia' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M.5L_Ia'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentManager' => ['privates', '.errored.Zx7dyAp', NULL, 'Cannot determine controller argument for "Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel::mongoCreate()": the $documentManager argument is type-hinted with the non-existent class or interface: "Doctrine\\ODM\\MongoDB\\DocumentManager".'],
        ], [
            'documentManager' => '?',
        ]);
    }
}
