<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_ConfigurationService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public '.zenstruck_foundry.configuration' shared service.
     *
     * @return \Zenstruck\Foundry\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Configuration.php';
        include_once \dirname(__DIR__, 6).'/FactoryRegistryInterface.php';
        include_once \dirname(__DIR__, 6).'/InMemory/InMemoryFactoryRegistry.php';
        include_once \dirname(__DIR__, 6).'/FakerAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Generator.php';
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Factory.php';
        include_once \dirname(__DIR__, 6).'/Object/Instantiator.php';
        include_once \dirname(__DIR__, 6).'/StoryRegistry.php';
        include_once \dirname(__DIR__, 6).'/InMemory/InMemoryRepositoryRegistry.php';
        include_once \dirname(__DIR__, 6).'/Persistence/PersistedObjectsTracker.php';

        return $container->services['.zenstruck_foundry.configuration'] = new \Zenstruck\Foundry\Configuration(new \Zenstruck\Foundry\InMemory\InMemoryFactoryRegistry(($container->privates['.zenstruck_foundry.in_memory.factory_registry.inner'] ?? $container->load('get_ZenstruckFoundry_InMemory_FactoryRegistry_InnerService'))), new \Zenstruck\Foundry\FakerAdapter(\Faker\Factory::create(), NULL, $container->getEnv('default::int:FOUNDRY_FAKER_SEED'), true), \Zenstruck\Foundry\Object\Instantiator::withConstructor(), new \Zenstruck\Foundry\StoryRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\CategoryStory'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\CategoryStory());
            yield 1 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory1'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\ConflictStory1());
            yield 2 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory2'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\ConflictStory2());
            yield 3 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ContactStory'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\ContactStory());
        }, 4), []), ($container->services['Zenstruck\\Foundry\\Persistence\\PersistenceManager'] ?? $container->load('getPersistenceManagerService')), true, new \Zenstruck\Foundry\InMemory\InMemoryRepositoryRegistry(($container->privates['.service_locator.dpiLQ5O'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))), ($container->privates['.foundry.persistence.objects_tracker'] ??= new \Zenstruck\Foundry\Persistence\PersistedObjectsTracker()), true, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
