<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_Behat_FactoryResolverService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public '.zenstruck_foundry.behat.factory_resolver' shared service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\FactoryShortNameResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/FactoryShortNameResolver.php';

        return $container->services['.zenstruck_foundry.behat.factory_resolver'] = new \Zenstruck\Foundry\Test\Behat\FactoryShortNameResolver(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Factories\\EntityWithUidFactory'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Factories\EntityWithUidFactory());
            yield 1 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Factories\\Tag\\TagFactory'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Factories\Tag\TagFactory());
            yield 2 => ($container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Factories\\TagFactory'] ??= new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Factories\TagFactory());
            yield 3 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\ArrayFactory'] ?? $container->load('getArrayFactoryService'));
            yield 4 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Document\\GenericDocumentFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Document\GenericDocumentFactory());
            yield 5 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Document\\GenericProxyDocumentFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Document\GenericProxyDocumentFactory());
            yield 6 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Address\\AddressFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\AddressFactory());
            yield 7 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Address\\ProxyAddressFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\ProxyAddressFactory());
            yield 8 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Category\\CategoryFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Category\CategoryFactory());
            yield 9 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Category\\ProxyCategoryFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Category\ProxyCategoryFactory());
            yield 10 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Contact\\ChildContactFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Contact\ChildContactFactory());
            yield 11 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Contact\\ContactFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Contact\ContactFactory());
            yield 12 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Contact\\ProxyContactFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Contact\ProxyContactFactory());
            yield 13 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\EdgeCases\\MultipleMandatoryRelationshipToSameEntity\\InversedSideEntityFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\EdgeCases\MultipleMandatoryRelationshipToSameEntity\InversedSideEntityFactory());
            yield 14 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\EdgeCases\\MultipleMandatoryRelationshipToSameEntity\\OwningSideEntityFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\EdgeCases\MultipleMandatoryRelationshipToSameEntity\OwningSideEntityFactory());
            yield 15 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\EmptyConstructorFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\EmptyConstructorFactory());
            yield 16 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\GenericEntityFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\GenericEntityFactory());
            yield 17 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\GenericProxyEntityFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\GenericProxyEntityFactory());
            yield 18 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Tag\\ProxyTagFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Tag\ProxyTagFactory());
            yield 19 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Tag\\TagFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Tag\TagFactory());
            yield 20 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\WithUniqueColumn\\WithUniqueColumnFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\WithUniqueColumn\WithUniqueColumnFactory());
            yield 21 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Object1Factory'] ?? $container->load('getObject1FactoryService'));
            yield 22 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Object2Factory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\Object2Factory());
            yield 23 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\SimpleObjectFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\SimpleObjectFactory());
            yield 24 => ($container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\WithHooksInInitializeFactory'] ??= new \Zenstruck\Foundry\Tests\Fixture\Factories\WithHooksInInitializeFactory());
        }, 25));
    }
}
