<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get__ZenstruckFoundry_Command_LoadFixtures_LazyService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '..zenstruck_foundry.command.load_fixtures.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['..zenstruck_foundry.command.load_fixtures.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('foundry:load-fixtures', ['foundry:load-stories', 'foundry:load-story'], 'Load stories which are marked with #[AsFixture] attribute.', false, #[\Closure(name: '.zenstruck_foundry.command.load_fixtures', class: 'Zenstruck\\Foundry\\Command\\LoadFixturesCommand')] fn (): \Zenstruck\Foundry\Command\LoadFixturesCommand => ($container->privates['.zenstruck_foundry.command.load_fixtures'] ?? $container->load('get_ZenstruckFoundry_Command_LoadFixturesService')));
    }
}
