<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressFactoryService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private 'Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\AddressFactory' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\AddressFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\Entity\\Address\\AddressFactory'] = new \Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\AddressFactory();
    }
}
