<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArrayFactoryService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private 'Zenstruck\Foundry\Tests\Fixture\Factories\ArrayFactory' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Tests\Fixture\Factories\ArrayFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Zenstruck\\Foundry\\Tests\\Fixture\\Factories\\ArrayFactory'] = new \Zenstruck\Foundry\Tests\Fixture\Factories\ArrayFactory(($container->services['router'] ?? self::getRouterService($container)));
    }
}
