<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBehat_Mink_ParametersService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'behat.mink.parameters' shared service.
     *
     * @return \FriendsOfBehat\SymfonyExtension\Mink\MinkParameters
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['behat.mink.parameters'] = new \ReflectionClass('FriendsOfBehat\SymfonyExtension\Mink\MinkParameters')->newLazyProxy(static fn () => self::do($container, false));
        }

        include_once \dirname(__DIR__, 4).'/vendor/friends-of-behat/symfony-extension/src/Mink/MinkParameters.php';

        return ($container->services['behat.service_container'] ?? $container->get('behat.service_container', 1))->get('fob_symfony.mink.parameters');
    }
}
