<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBehat_Mink_DefaultSessionService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'behat.mink.default_session' shared service.
     *
     * @return \Behat\Mink\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['behat.mink.default_session'] = new \ReflectionClass('Behat\Mink\Session')->newLazyProxy(static fn () => self::do($container, false));
        }

        include_once \dirname(__DIR__, 4).'/vendor/behat/mink/src/Session.php';

        return ($container->services['behat.mink'] ?? $container->load('getBehat_MinkService'))->getSession();
    }
}
