<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBehat_MinkService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'behat.mink' shared service.
     *
     * @return \Behat\Mink\Mink
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['behat.mink'] = new \ReflectionClass('Behat\Mink\Mink')->newLazyProxy(static fn () => self::do($container, false));
        }

        include_once \dirname(__DIR__, 4).'/vendor/behat/mink/src/Mink.php';

        return ($container->services['behat.service_container'] ?? $container->get('behat.service_container', 1))->get('fob_symfony.mink');
    }
}
