<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBehat_Driver_ServiceContainerService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'behat.driver.service_container' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ContainerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['behat.driver.service_container'] = $container->createProxy('ContainerInterfaceProxyA154646', static fn () => \ContainerInterfaceProxyA154646::createLazyProxy(static fn () => self::do($container, false)));
        }

        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/KernelInterface.php';

        return [[($container->services['behat.service_container'] ?? $container->get('behat.service_container', 1))->get('fob_symfony.driver_kernel'), 'getContainer'](), 'get']('test.service_container');
    }
}
