<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConflictStory2Service extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private 'Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\ConflictStory2' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\ConflictStory2
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Story.php';
        include_once \dirname(__DIR__, 4).'/tests/Fixture/Stories/ConflictStory2.php';

        return $container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Stories\\ConflictStory2'] = new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Stories\ConflictStory2();
    }
}
