<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateGenericModelService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'Zenstruck\Foundry\Tests\Fixture\App\Controller\CreateGenericModel' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Tests\Fixture\App\Controller\CreateGenericModel
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel'] = new \Zenstruck\Foundry\Tests\Fixture\App\Controller\CreateGenericModel();
    }
}
