<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteGenericModelormDbDeleteService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.3BoFVFw.Zenstruck\Foundry\Tests\Fixture\App\Controller\DeleteGenericModel::ormDbDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3BoFVFw.Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDbDelete()'] = ($container->privates['.service_locator.3BoFVFw'] ?? $container->load('get_ServiceLocator_3BoFVFwService'))->withContext('Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel::ormDbDelete()', $container);
    }
}
