<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDama_Doctrine_Dbal_Middleware_Default_DefaultService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private 'dama.doctrine.dbal.middleware.default.default' shared service.
     *
     * @return \DAMA\DoctrineTestBundle\Doctrine\DBAL\Middleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Driver/Middleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/dama/doctrine-test-bundle/src/Doctrine/DBAL/Middleware.php';

        return $container->privates['dama.doctrine.dbal.middleware.default.default'] = new \DAMA\DoctrineTestBundle\Doctrine\DBAL\Middleware();
    }
}
