<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityWithUidFactoryService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private 'Zenstruck\Foundry\Test\Behat\Tests\Fixture\Factories\EntityWithUidFactory' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Factories\EntityWithUidFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Factory.php';
        include_once \dirname(__DIR__, 6).'/ObjectFactory.php';
        include_once \dirname(__DIR__, 6).'/Persistence/PersistentObjectFactory.php';
        include_once \dirname(__DIR__, 4).'/tests/Fixture/Factories/EntityWithUidFactory.php';

        return $container->privates['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\Factories\\EntityWithUidFactory'] = new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\Factories\EntityWithUidFactory();
    }
}
