<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoundryContextService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'Zenstruck\Foundry\Test\Behat\FoundryContext' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\FoundryContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/FoundryContext.php';

        return $container->services['Zenstruck\\Foundry\\Test\\Behat\\FoundryContext'] = new \Zenstruck\Foundry\Test\Behat\FoundryContext(($container->services['.zenstruck_foundry.behat.factory_resolver'] ?? $container->load('get_ZenstruckFoundry_Behat_FactoryResolverService')), ($container->services['.zenstruck_foundry.behat.object_registry'] ?? $container->load('get_ZenstruckFoundry_Behat_ObjectRegistryService')));
    }
}
