<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersistenceManagerService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'Zenstruck\Foundry\Persistence\PersistenceManager' shared service.
     *
     * @return \Zenstruck\Foundry\Persistence\PersistenceManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/Persistence/IdentifierResolver.php';
        include_once \dirname(__DIR__, 6).'/Persistence/PersistenceManager.php';
        include_once \dirname(__DIR__, 6).'/Persistence/ResetDatabase/ResetDatabaseManager.php';

        return $container->services['Zenstruck\\Foundry\\Persistence\\PersistenceManager'] = new \Zenstruck\Foundry\Persistence\PersistenceManager(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.zenstruck_foundry.persistence_strategy.orm'] ?? $container->load('get_ZenstruckFoundry_PersistenceStrategy_OrmService'));
        }, 1), new \Zenstruck\Foundry\Persistence\ResetDatabase\ResetDatabaseManager(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.zenstruck_foundry.persistence.database_resetter.orm.dama'] ?? $container->load('get_ZenstruckFoundry_Persistence_DatabaseResetter_Orm_DamaService'));
        }, 1), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.zenstruck_foundry.persistence.database_resetter.orm.dama'] ?? $container->load('get_ZenstruckFoundry_Persistence_DatabaseResetter_Orm_DamaService'));
        }, 1)));
    }
}
