<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetDisabledTestContextService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'Zenstruck\Foundry\Test\Behat\Tests\Fixture\ResetDisabledTestContext' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\Tests\Fixture\ResetDisabledTestContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/tests/Fixture/ResetDisabledTestContext.php';

        return $container->services['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\ResetDisabledTestContext'] = new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\ResetDisabledTestContext(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
