<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_Loader_Attribute_ServicesService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the private 'routing.loader.attribute.services' shared service.
     *
     * @return \Symfony\Component\Routing\Loader\AttributeServicesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Loader/AttributeServicesLoader.php';

        return $container->privates['routing.loader.attribute.services'] = new \Symfony\Component\Routing\Loader\AttributeServicesLoader(['Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\HelloWorldController', 'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\UpdateGenericModel', 'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\CreateGenericModel', 'Zenstruck\\Foundry\\Tests\\Fixture\\App\\Controller\\DeleteGenericModel']);
    }
}
