<?php

namespace ContainerJexmdIG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestFoundryContextService extends Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer
{
    /**
     * Gets the public 'Zenstruck\Foundry\Test\Behat\Tests\Fixture\TestFoundryContext' shared autowired service.
     *
     * @return \Zenstruck\Foundry\Test\Behat\Tests\Fixture\TestFoundryContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/vendor/yceruto/behat-extension/src/Context/ExceptionAssertionTrait.php';
        include_once \dirname(__DIR__, 4).'/tests/Fixture/TestFoundryContext.php';

        return $container->services['Zenstruck\\Foundry\\Test\\Behat\\Tests\\Fixture\\TestFoundryContext'] = new \Zenstruck\Foundry\Test\Behat\Tests\Fixture\TestFoundryContext();
    }
}
