<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJexmdIG\Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJexmdIG/Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJexmdIG.legacy');

    return;
}

if (!\class_exists(Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJexmdIG\Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer::class, Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer::class, false);
}

return new \ContainerJexmdIG\Zenstruck_Foundry_Test_Behat_Tests_Fixture_BehatTestKernelTestDebugContainer([
    'container.build_hash' => 'JexmdIG',
    'container.build_id' => '536b1e1b',
    'container.build_time' => 1784568102,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJexmdIG');
